setup: &setup
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5

development:
  <<: *setup
  database: rails_integration_demo_development

test:
  <<: *setup
  database: rails_integration_demo_test

staging:
  <<: *setup
  database: rails_integration_demo_staging

production:
  <<: *setup
  database: rails_integration_demo_production

cucumber:
  <<: *test